#!/usr/bin/env bash

f="$(mktemp)"
trap "rm '$f'" 0 # remove temp file at exit
cat > "$f"
"${EDITOR:-vim}" "$f" > /dev/tty
ee="$?"
if [ "$ee" == "0" ]; then
	cat "$f"
else
	echo "Editor exited with code $ee, and not success exit code" 1>&2
	exit "$ee"
fi
